// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/arangodb/go-driver/v2/arangodb (interfaces: Cursor)
//
// Generated by this command:
//
//      mockgen -package=mocks github.com/arangodb/go-driver/v2/arangodb Cursor
//

// Package mocks is a generated GoMock package.
package mocks

import (
        context "context"
        reflect "reflect"

        arangodb "github.com/arangodb/go-driver/v2/arangodb"
        gomock "go.uber.org/mock/gomock"
)

// MockCursor is a mock of Cursor interface.
type MockCursor struct {
        ctrl     *gomock.Controller
        recorder *MockCursorMockRecorder
        isgomock struct{}
}

// MockCursorMockRecorder is the mock recorder for MockCursor.
type MockCursorMockRecorder struct {
        mock *MockCursor
}

// NewMockCursor creates a new mock instance.
func NewMockCursor(ctrl *gomock.Controller) *MockCursor {
        mock := &MockCursor{ctrl: ctrl}
        mock.recorder = &MockCursorMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCursor) EXPECT() *MockCursorMockRecorder {
        return m.recorder
}

// Close mocks base method.
func (m *MockCursor) Close() error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Close")
        ret0, _ := ret[0].(error)
        return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCursorMockRecorder) Close() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCursor)(nil).Close))
}

// CloseWithContext mocks base method.
func (m *MockCursor) CloseWithContext(ctx context.Context) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "CloseWithContext", ctx)
        ret0, _ := ret[0].(error)
        return ret0
}

// CloseWithContext indicates an expected call of CloseWithContext.
func (mr *MockCursorMockRecorder) CloseWithContext(ctx any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseWithContext", reflect.TypeOf((*MockCursor)(nil).CloseWithContext), ctx)
}

// Count mocks base method.
func (m *MockCursor) Count() int64 {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Count")
        ret0, _ := ret[0].(int64)
        return ret0
}

// Count indicates an expected call of Count.
func (mr *MockCursorMockRecorder) Count() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockCursor)(nil).Count))
}

// HasMore mocks base method.
func (m *MockCursor) HasMore() bool {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "HasMore")
        ret0, _ := ret[0].(bool)
        return ret0
}

// HasMore indicates an expected call of HasMore.
func (mr *MockCursorMockRecorder) HasMore() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMore", reflect.TypeOf((*MockCursor)(nil).HasMore))
}

// Plan mocks base method.
func (m *MockCursor) Plan() arangodb.CursorPlan {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Plan")
        ret0, _ := ret[0].(arangodb.CursorPlan)
        return ret0
}

// Plan indicates an expected call of Plan.
func (mr *MockCursorMockRecorder) Plan() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plan", reflect.TypeOf((*MockCursor)(nil).Plan))
}

// ReadDocument mocks base method.
func (m *MockCursor) ReadDocument(ctx context.Context, result any) (arangodb.DocumentMeta, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "ReadDocument", ctx, result)
        ret0, _ := ret[0].(arangodb.DocumentMeta)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// ReadDocument indicates an expected call of ReadDocument.
func (mr *MockCursorMockRecorder) ReadDocument(ctx, result any) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDocument", reflect.TypeOf((*MockCursor)(nil).ReadDocument), ctx, result)
}

// Statistics mocks base method.
func (m *MockCursor) Statistics() arangodb.CursorStats {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "Statistics")
        ret0, _ := ret[0].(arangodb.CursorStats)
        return ret0
}

// Statistics indicates an expected call of Statistics.
func (mr *MockCursorMockRecorder) Statistics() *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statistics", reflect.TypeOf((*MockCursor)(nil).Statistics))
}