// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "is_critical", Type: field.TypeBool, Default: false},
		{Name: "is_protected", Type: field.TypeBool, Default: false},
		{Name: "preferred_channel", Type: field.TypeString},
		{Name: "template", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "event_name",
				Unique:  true,
				Columns: []*schema.Column{EventsColumns[1]},
			},
			{
				Name:    "event_preferred_channel_name",
				Unique:  false,
				Columns: []*schema.Column{EventsColumns[5], EventsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
	}
)

func init() {
}
