// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventResponseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*EventResponse       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponseList) Reset() {
	*x = EventResponseList{}
	mi := &file_proto_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponseList) ProtoMessage() {}

func (x *EventResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponseList.ProtoReflect.Descriptor instead.
func (*EventResponseList) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventResponseList) GetEvents() []*EventResponse {
	if x != nil {
		return x.Events
	}
	return nil
}

type RemoveEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveEventResponse) Reset() {
	*x = RemoveEventResponse{}
	mi := &file_proto_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveEventResponse) ProtoMessage() {}

func (x *RemoveEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveEventResponse.ProtoReflect.Descriptor instead.
func (*RemoveEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsCritical       bool                   `protobuf:"varint,2,opt,name=is_critical,json=isCritical,proto3" json:"is_critical,omitempty"`
	PreferredChannel string                 `protobuf:"bytes,3,opt,name=preferred_channel,json=preferredChannel,proto3" json:"preferred_channel,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_proto_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventRequest) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

func (x *CreateEventRequest) GetPreferredChannel() string {
	if x != nil {
		return x.PreferredChannel
	}
	return ""
}

type GetEventByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventByNameRequest) Reset() {
	*x = GetEventByNameRequest{}
	mi := &file_proto_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventByNameRequest) ProtoMessage() {}

func (x *GetEventByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventByNameRequest.ProtoReflect.Descriptor instead.
func (*GetEventByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EventResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsCritical       bool                   `protobuf:"varint,3,opt,name=is_critical,json=isCritical,proto3" json:"is_critical,omitempty"`
	PreferredChannel string                 `protobuf:"bytes,4,opt,name=preferred_channel,json=preferredChannel,proto3" json:"preferred_channel,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_proto_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_proto_event_proto_rawDescGZIP(), []int{4}
}

func (x *EventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventResponse) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

func (x *EventResponse) GetPreferredChannel() string {
	if x != nil {
		return x.PreferredChannel
	}
	return ""
}

func (x *EventResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EventResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_event_proto protoreflect.FileDescriptor

const file_proto_event_proto_rawDesc = "" +
	"\n" +
	"\x11proto/event.proto\x12\fnotification\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n" +
	"\x11EventResponseList\x123\n" +
	"\x06events\x18\x01 \x03(\v2\x1b.notification.EventResponseR\x06events\"/\n" +
	"\x13RemoveEventResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"v\n" +
	"\x12CreateEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vis_critical\x18\x02 \x01(\bR\n" +
	"isCritical\x12+\n" +
	"\x11preferred_channel\x18\x03 \x01(\tR\x10preferredChannel\"+\n" +
	"\x15GetEventByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xf7\x01\n" +
	"\rEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vis_critical\x18\x03 \x01(\bR\n" +
	"isCritical\x12+\n" +
	"\x11preferred_channel\x18\x04 \x01(\tR\x10preferredChannel\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xd0\x02\n" +
	"\fEventService\x12L\n" +
	"\vCreateEvent\x12 .notification.CreateEventRequest\x1a\x1b.notification.EventResponse\x12R\n" +
	"\x0eGetEventByName\x12#.notification.GetEventByNameRequest\x1a\x1b.notification.EventResponse\x12G\n" +
	"\fGetAllEvents\x12\x16.google.protobuf.Empty\x1a\x1f.notification.EventResponseList\x12U\n" +
	"\vRemoveEvent\x12#.notification.GetEventByNameRequest\x1a!.notification.RemoveEventResponseB\x0fZ\r/proto/event/b\x06proto3"

var (
	file_proto_event_proto_rawDescOnce sync.Once
	file_proto_event_proto_rawDescData []byte
)

func file_proto_event_proto_rawDescGZIP() []byte {
	file_proto_event_proto_rawDescOnce.Do(func() {
		file_proto_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)))
	})
	return file_proto_event_proto_rawDescData
}

var file_proto_event_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_event_proto_goTypes = []any{
	(*EventResponseList)(nil),     // 0: notification.EventResponseList
	(*RemoveEventResponse)(nil),   // 1: notification.RemoveEventResponse
	(*CreateEventRequest)(nil),    // 2: notification.CreateEventRequest
	(*GetEventByNameRequest)(nil), // 3: notification.GetEventByNameRequest
	(*EventResponse)(nil),         // 4: notification.EventResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_proto_event_proto_depIdxs = []int32{
	4, // 0: notification.EventResponseList.events:type_name -> notification.EventResponse
	5, // 1: notification.EventResponse.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: notification.EventResponse.updated_at:type_name -> google.protobuf.Timestamp
	2, // 3: notification.EventService.CreateEvent:input_type -> notification.CreateEventRequest
	3, // 4: notification.EventService.GetEventByName:input_type -> notification.GetEventByNameRequest
	6, // 5: notification.EventService.GetAllEvents:input_type -> google.protobuf.Empty
	3, // 6: notification.EventService.RemoveEvent:input_type -> notification.GetEventByNameRequest
	4, // 7: notification.EventService.CreateEvent:output_type -> notification.EventResponse
	4, // 8: notification.EventService.GetEventByName:output_type -> notification.EventResponse
	0, // 9: notification.EventService.GetAllEvents:output_type -> notification.EventResponseList
	1, // 10: notification.EventService.RemoveEvent:output_type -> notification.RemoveEventResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_event_proto_init() }
func file_proto_event_proto_init() {
	if File_proto_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_event_proto_rawDesc), len(file_proto_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_event_proto_goTypes,
		DependencyIndexes: file_proto_event_proto_depIdxs,
		MessageInfos:      file_proto_event_proto_msgTypes,
	}.Build()
	File_proto_event_proto = out.File
	file_proto_event_proto_goTypes = nil
	file_proto_event_proto_depIdxs = nil
}
