syntax = "proto3";

package notification;
option go_package = "/proto/event/";

import "google/protobuf/timestamp.proto"; 
import "google/protobuf/empty.proto"; 

service EventService {
    rpc CreateEvent (CreateEventRequest) returns (EventResponse);
    rpc GetEventByName (GetEventByNameRequest) returns (EventResponse);
    rpc GetAllEvents (google.protobuf.Empty) returns (EventResponseList);
    rpc RemoveEvent (GetEventByNameRequest) returns (RemoveEventResponse);
}

message EventResponseList {
    repeated EventResponse events = 1;
}

message RemoveEventResponse {
    string message = 1;
}


message CreateEventRequest {
    string name = 1;
    bool is_critical = 2;
    bool is_protected = 3;
    string preferred_channel = 4;
    string template = 5;
}

message GetEventByNameRequest {
    string name = 1;
}

message EventResponse {
    string id = 1;
    string name = 2;
    bool is_critical = 3;
    bool is_protected = 4;
    string preferred_channel = 5;
    string template = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}