// Code generated by ent, DO NOT EDIT.

package event

import (
	"hermesx/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldName, v))
}

// IsCritical applies equality check predicate on the "is_critical" field. It's identical to IsCriticalEQ.
func IsCritical(v bool) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldIsCritical, v))
}

// IsProtected applies equality check predicate on the "is_protected" field. It's identical to IsProtectedEQ.
func IsProtected(v bool) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldIsProtected, v))
}

// PreferredChannel applies equality check predicate on the "preferred_channel" field. It's identical to PreferredChannelEQ.
func PreferredChannel(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPreferredChannel, v))
}

// Template applies equality check predicate on the "template" field. It's identical to TemplateEQ.
func Template(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTemplate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldName, v))
}

// IsCriticalEQ applies the EQ predicate on the "is_critical" field.
func IsCriticalEQ(v bool) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldIsCritical, v))
}

// IsCriticalNEQ applies the NEQ predicate on the "is_critical" field.
func IsCriticalNEQ(v bool) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldIsCritical, v))
}

// IsProtectedEQ applies the EQ predicate on the "is_protected" field.
func IsProtectedEQ(v bool) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldIsProtected, v))
}

// IsProtectedNEQ applies the NEQ predicate on the "is_protected" field.
func IsProtectedNEQ(v bool) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldIsProtected, v))
}

// PreferredChannelEQ applies the EQ predicate on the "preferred_channel" field.
func PreferredChannelEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldPreferredChannel, v))
}

// PreferredChannelNEQ applies the NEQ predicate on the "preferred_channel" field.
func PreferredChannelNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldPreferredChannel, v))
}

// PreferredChannelIn applies the In predicate on the "preferred_channel" field.
func PreferredChannelIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldPreferredChannel, vs...))
}

// PreferredChannelNotIn applies the NotIn predicate on the "preferred_channel" field.
func PreferredChannelNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldPreferredChannel, vs...))
}

// PreferredChannelGT applies the GT predicate on the "preferred_channel" field.
func PreferredChannelGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldPreferredChannel, v))
}

// PreferredChannelGTE applies the GTE predicate on the "preferred_channel" field.
func PreferredChannelGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldPreferredChannel, v))
}

// PreferredChannelLT applies the LT predicate on the "preferred_channel" field.
func PreferredChannelLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldPreferredChannel, v))
}

// PreferredChannelLTE applies the LTE predicate on the "preferred_channel" field.
func PreferredChannelLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldPreferredChannel, v))
}

// PreferredChannelContains applies the Contains predicate on the "preferred_channel" field.
func PreferredChannelContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldPreferredChannel, v))
}

// PreferredChannelHasPrefix applies the HasPrefix predicate on the "preferred_channel" field.
func PreferredChannelHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldPreferredChannel, v))
}

// PreferredChannelHasSuffix applies the HasSuffix predicate on the "preferred_channel" field.
func PreferredChannelHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldPreferredChannel, v))
}

// PreferredChannelEqualFold applies the EqualFold predicate on the "preferred_channel" field.
func PreferredChannelEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldPreferredChannel, v))
}

// PreferredChannelContainsFold applies the ContainsFold predicate on the "preferred_channel" field.
func PreferredChannelContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldPreferredChannel, v))
}

// TemplateEQ applies the EQ predicate on the "template" field.
func TemplateEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldTemplate, v))
}

// TemplateNEQ applies the NEQ predicate on the "template" field.
func TemplateNEQ(v string) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldTemplate, v))
}

// TemplateIn applies the In predicate on the "template" field.
func TemplateIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldTemplate, vs...))
}

// TemplateNotIn applies the NotIn predicate on the "template" field.
func TemplateNotIn(vs ...string) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldTemplate, vs...))
}

// TemplateGT applies the GT predicate on the "template" field.
func TemplateGT(v string) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldTemplate, v))
}

// TemplateGTE applies the GTE predicate on the "template" field.
func TemplateGTE(v string) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldTemplate, v))
}

// TemplateLT applies the LT predicate on the "template" field.
func TemplateLT(v string) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldTemplate, v))
}

// TemplateLTE applies the LTE predicate on the "template" field.
func TemplateLTE(v string) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldTemplate, v))
}

// TemplateContains applies the Contains predicate on the "template" field.
func TemplateContains(v string) predicate.Event {
	return predicate.Event(sql.FieldContains(FieldTemplate, v))
}

// TemplateHasPrefix applies the HasPrefix predicate on the "template" field.
func TemplateHasPrefix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasPrefix(FieldTemplate, v))
}

// TemplateHasSuffix applies the HasSuffix predicate on the "template" field.
func TemplateHasSuffix(v string) predicate.Event {
	return predicate.Event(sql.FieldHasSuffix(FieldTemplate, v))
}

// TemplateIsNil applies the IsNil predicate on the "template" field.
func TemplateIsNil() predicate.Event {
	return predicate.Event(sql.FieldIsNull(FieldTemplate))
}

// TemplateNotNil applies the NotNil predicate on the "template" field.
func TemplateNotNil() predicate.Event {
	return predicate.Event(sql.FieldNotNull(FieldTemplate))
}

// TemplateEqualFold applies the EqualFold predicate on the "template" field.
func TemplateEqualFold(v string) predicate.Event {
	return predicate.Event(sql.FieldEqualFold(FieldTemplate, v))
}

// TemplateContainsFold applies the ContainsFold predicate on the "template" field.
func TemplateContainsFold(v string) predicate.Event {
	return predicate.Event(sql.FieldContainsFold(FieldTemplate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Event {
	return predicate.Event(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Event {
	return predicate.Event(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Event) predicate.Event {
	return predicate.Event(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Event) predicate.Event {
	return predicate.Event(sql.NotPredicates(p))
}
